const Actions = {
  GET_RELY_MAILS_BY_ID_REQUEST: 'GET_RELY_MAILS_BY_ID_REQUEST',
  GET_RELY_MAILS_BY_ID_RESPONSE: 'GET_RELY_MAILS_BY_ID_RESPONSE',

  GetFeedbackMailsId: id => ({
    type: Actions.GET_RELY_MAILS_BY_ID_REQUEST,
    id
  }),

  ADD_FEEDBACK_MAIL_REQUEST: 'ADD_FEEDBACK_MAIL_REQUEST',
  ADD_FEEDBACK_MAIL_RESPONSE: 'ADD_FEEDBACK_MAIL_RESPONSE',

  AddFeedbackMail: data => ({
    type: Actions.ADD_FEEDBACKMAIL_REQUEST,
    data
  }),

  EDIT_FEEDBACK_MAILS_REQUEST: 'EDIT_FEEDBACK_MAILS_REQUEST',
  EDIT_FEEDBACK_MAILS_RESPONSE: 'EDIT_FEEDBACK_MAILS_RESPONSE',

  EditFeedbackMails: data => ({
    type: Actions.EDIT_FEEDBACK_MAILS_REQUEST,
    data
  }),

  GET_FEEDBACK_DETAIL: 'GET_FEEDBACK_DETAIL',

  GetDetailMails: data => ({
    type: Actions.GET_FEEDBACK_DETAIL,
    data
  })
};
export default Actions;
